trigger:
  branches:
    include:
      - "*"

pool:
  name: 'DEFRA-COMMON-UBUNTU-SSV5'

resources:
  repositories:
    - repository: ipaffs-infra
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-infra
      ref: refs/heads/main

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    values:
      - DEV
      - TST
      - PRE
      - PRD
    default: DEV

variables:
  - group: "${{ parameters.environmentName }}"
  - name: serviceName
    value: notify

stages:
  - template: /pipelines/templates/java-template.yaml@ipaffs-infra
    parameters:
      environmentName: "${{ parameters.environmentName }}"
      serviceName: "${{ variables.serviceName }}"

# vim: set ts=2 sts=2 sw=2 et:
