service: notify-service

container:
  replicas: 1

serviceBus:
  enabled: true

keda:
  enabled: true
  pollingInterval: 30
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

externalSecret:
  enabled: true
  refreshInterval: 1h
  secrets:
    - secretKey: TRADE_PLATFORM_CLIENT_SECRET
      remoteKey: tradePlatformClientSecret
    - secretKey: TRADE_PLATFORM_SUBSCRIPTION_KEY
      remoteKey: tradePlatformSubscriptionKey
