env:
  - name: NOTIFY_QUEUE_NAME
    value: "notify_queue"
  - name: NOTIFY_QUEUE_CONNECTION_NAME
    valueFrom:
      secretKeyRef:
        name: notify-service-servicebus
        key: SERVICE_BUS_CONNECTION_STRING
        optional: true
  - name: ENABLE_EMAIL_NOTIFICATION
    value: "true"
  - name: ENABLE_TEXT_NOTIFICATION
    value: "true"
  - name: TRADE_PLATFORM_NOTIFY_URL
    value: "https://pre-internal-gateway.trade.azure.defra.cloud/trade-notify/v1"
  - name: TRADE_PLATFORM_SYSTEM_NAME
    value: "IPAFFS"
  - name: TRADE_PLATFORM_SYSTEM_UNIQUE_ID
    value: "38BC514D-FC26-47BF-99C2-6FCACF581AF5"
  - name: API_VERSION
    value: "1.0.0"

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "500m"
    memory: 1Gi
